### ISSUE TITLE
Option to allow leniency/exemption when a plugin teleports a player rapidly

### ISSUE THREAD

**Issue by RoboMWM** [asofold/CompatNoCheatPlus#7]
I'm not sure if I should request this here or in the regular NCP repo but I'd like an option to temporarily exempt a player from checks when being rapidly teleported with velocity - this happens with the PortalStick plugin, which should tell you more than enough of how it could easily cause violations when players put themselves in a portal loop or similar.

**Comment by RoboMWM** [comment]
Actually I'm no longer having issues with this since build 911. Interesting.

**Comment by asofold** [comment]
Slightly bumpy ride here - latest fix for stuff with join/teleport/respawn would be build 913.
